---

- name: Apply or remove standard router template with config_manager
  hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    erase: false

  tasks:

  - block:
    - name: Retrieve network element configuration
      include_role:
        public: yes
        name: ansible-network.config_manager
        tasks_from: get

    - name: print out configuration
      debug:
        var: configuration

    - name: Place configurations into file
      copy:
        dest: "./configs/{{ inventory_hostname }}.cfg"
        content: "{{ configuration }}"
    when: not erase | bool

  - name: Delete configuration files
    file:
      path: "./configs/{{ inventory_hostname }}.cfg"
      state: absent
    when: erase | bool
